---
title: Le Guess Who? 2019 playlists
author: Arjan
date: '2019-11-04'
slug: le-guess-who-2019-playlists
categories: []
tags:
  - Music
  - LGW
  - Bandcamp
  - Utrecht
  - Festival
comments: no
images: ~
---

Since 2007 there's [Le Guess Who?][12] (LGW) festival in my home town. Me and friends love to attend it, browse the venues, and see heaps of awesome bands, year after year.  

Every year I start out making a sheet with all bands, subdivided by day, try to listen to at least one album per band, and color code all bands from red (don't like it at all) to light green (love it!). With the evergrowing program, I don't think I've made it through the entire program in recent years - which actually might be a good thing; apparently I have other things to do, too. ;)  
This year I put my favourite song of bands that I liked (dark green) and loved (light green) in play lists. So, for everyone that didn't have the time to check out everything yet, here's a selection for the Thursday and Friday. I haven't gone through Saturday yet, and since I'm DJing on Sunday (TivoliVredenburg Pandora; just a concert DJ, nothing special, but good clean fun), I'm probably not going to bother to check out all other bands that day, since I won't be seeing them anyway; no reason to get exited over things I can't attend.  

*No Spotify*  
Since LGW only offers links to Spotify on their own website, I wanted to make a few playlists that don't rely on this Swedish juggernaut. I don't have a Spotify account, and don't want one for various reasons, amongst others triggered by the writings of Damon Krukowski of Galaxy 500 on Pitchfork: [here][3] and [here][4]; the Bandcamp year in [review][5] [blogs][6]; and other articles e.g. on [Vox][7], and [PasteMagazine][8]. I do have to admit, some articles I recently read surprised me, in a [positive][9] [way][10], although I remain sceptical concerning Spotify, other major streaming services like Google Music and Apple Music, and the three major record labels.  

*Bandcamp*  
Ultimately, I chose to use [Playmoss][1] to make my playlists. In these playlists you will only find tracks that I selected from [Bandcamp][2], my favourite place to find music. Every song in the playlists has a link to the original Bandcamp page, where you can buy the music in digital (various file formats) and/or phsyical format (records, cassettes, cd's). Bandcamp itself does not offer a playlist function. What it does offer is a great website focusing on a meriad of types of music, highlighting unknown bands and music styles on a daily basis. I would expect the people behind LGW would appreciate a platform like this, sporting the majority of the bands on LGW festival, including their music for stream and for sale.  

*2019 program*  
Concerning this year's LGW program, I have to say, again it's hard to choose.  
**Thursday** was relatively easy, since the number of artists was limited. My clear favourites there are [Vicky Chow][13], that I remember releasing 'Tristan Perich: Surface Image', and of whom the new work on 'Michael Gordon: Sonatra' again is stunning; [Greg Fox][15]; [OSHUN][14]; and [William Tyler][16] & [Mary Lattimore][17] (recent solo albums of these two artists are excellent; teaming up in this case!).  
**Friday**'s program is a bit more elaborate, so more acts didn't make the cut for the play list. Here, my favourites are [Not Waving & Dark Mark][18] (Mark Lanegan!); [Oiseaux-Tempête][19] & Friends (with GW Sok, ex-The Ex, on the latest release; beautiful); [Richard Youngs][20] (recently saw him in [Worm][11], Rotterdam as part of the Youngs, Maranha, Corsano trio); [Idris Ackamoor & The Pyramids][21]; and [Lightning Bolt][22].  

Fun times!  

# **Thursday** playlist
<iframe width="100%" height="468" src="//playmoss.com/embed/ab/le-guess-who-festival-2019-friday?skin=dark" frameborder="0" allowfullscreen></iframe>

# **Friday** playlist
<iframe width="100%" height="468" src="//playmoss.com/embed/ab/le-guess-who-festival-2019-thursday?skin=dark" frameborder="0" allowfullscreen></iframe>



[1]: https://playmoss.com/
[2]: https://bandcamp.com/
[3]: https://pitchfork.com/features/oped/how-to-be-a-responsible-music-fan-in-the-age-of-streaming/
[4]: https://pitchfork.com/features/article/8993-the-cloud/
[5]: https://daily.bandcamp.com/2017/01/24/everything-is-terrific-the-bandcamp-2016-year-in-review/
[6]: https://daily.bandcamp.com/2018/02/12/the-bandcamp-2017-year-in-review/
[7]: https://www.vox.com/2018/4/3/17191390/spotify-plan-big-music-labels-platform-marketplace-ipo
[8]: https://www.pastemagazine.com/articles/2019/06/petal-spotify-independent-record-store-thread.html
[9]: https://www.recordoftheday.com/news-and-press/rotd-analyses-the-indie-major-label-split-on-prominent-spotify-playlists-to-examine-whether-fears-around-a-major-label-dominance-are-founded-
[10]: https://www.musicbusinessworldwide.com/the-major-labels-are-starting-to-find-life-tougher-in-sweden-is-this-is-a-wake-up-call-for-the-future/
[11]: https://worm.org/production/youngs-maranha-corsano-flowers-ghosts-echoes-2/
[12]: https://leguesswho.nl/
[13]: https://vickychow.bandcamp.com/
[14]: https://oshuniverse.bandcamp.com/
[15]: https://gregfox.bandcamp.com/
[16]: https://williamtyler.bandcamp.com/album/goes-west
[17]: https://marylattimoreharpist.bandcamp.com/album/hundreds-of-days
[18]: https://ecstaticrecordings.bandcamp.com/album/downwelling
[19]: https://oiseaux-tempete.bandcamp.com/
[20]: https://nofansrecords.bandcamp.com/
[21]: https://idrisackamoorandthepyramids.bandcamp.com/album/an-angel-fell
[22]: https://lightningbolt.bandcamp.com/album/sonic-citadel