---
title: Fix KSysGuard - not valid XML
author: Arjan
date: '2020-06-08'
slug: fix-ksysguard-not-valid-xml
categories: []
tags:
  - Kubuntu
  - Linux
  - Ubuntu
  - ProcessTable
  - SystemLoad2
  - XML
  - KSysGuard
comments: no
images: ~
---

After cleaning my `syslog` and `kern.log` recently, like I described [earlier](https://tinyspheresof.netlify.app/2020/05/17/cleaning-up-my-kubuntu-os/) - my system drive was full due to (among others) bloated log files (7.7GB each this time) - I found that KSysGuard doesn't start properly. I received the following errors, upon which KSysGuard opens its screen without any content: no process table, no CPU usage table.  

Error messages:  

    The file /home/ab/.local/ksysguard/ProcessTable.sgrd does not contain valid XML
    The file /home/ab/.local/ksysguard/SystemLoad2.sgrd does not contain valid XML

Upon a [search](https://duckduckgo.com/?q=ksysguard+ProcessTable.sgrd+does+not+contain+valid+XML+ubuntu) in `duckduckgo`, I came accross a [similar issue](https://askubuntu.com/questions/543750/ksysguard-give-error-the-file-home-mahesh-kde-share-apps-ksysguard-processtabl) on StackExchange dating already from 2014, with an updated answer from 2018, after KDE5 implementation. This most recent answer suggests the following for `ProcessTable.sgrd`:  
```{bash copy_xml_example, eval = FALSE}
sudo cp /usr/share/ksysguard/ProcessTable.sgrd /home/[youruser]/.local/share/ksysguard/ProcessTable.sgrd
```

So, for me that would be:  
```{bash copy_xml, eval = FALSE}
sudo cp /usr/share/ksysguard/ProcessTable.sgrd /home/ab/.local/share/ksysguard/ProcessTable.sgrd
sudo cp /usr/share/ksysguard/SystemLoad2.sgrd /home/ab/.local/share/ksysguard/SystemLoad2.sgrd
```

This works like a charm.  

And in my case I don't need to point to the local directory, as suggested in the answer, since the files are picked up automatically by KSysGuard after copying them.  

Interestingly enough, the answer mentions that this happened after cleaning cache and rebooting too fast. Besides emptying abovementioned log files, I emptied journal log and browser data, before this happened. It is unclear to me whether this underlies the issue at hand, and if so, why that would be so.  